### PR TITLE
fix TypeError when accessing TetGen.mesh property

### PR DESCRIPTION
**Pull request by darikg**
I'm using numpy 1.18.5 on windows and I was getting `TypeError: Indices must be either a mask or an integer array-like` when trying to access `TetGen.mesh`. Specifying the dtype of the triangles array in that method as int fixes it.

### CODE REVIEW

**Comment by akaszynski** [comment]
Thanks for the fix!  Looks like there's an issue when uploading to PyPi testing when outside the main repo.  I've disabled that so we don't run into these issues in the future.

**Comment by darikg** [comment]
Ah, thanks for fixing the tests, I was a little confused there

**Comment by akaszynski** [comment]
This fix is live on PyPy as `tetgen==0.5.1`

**Comment by darikg** [comment]
thanks @akaszynski !

**Pull request merged**
